services:
  talkvera-web:
    build: .
    container_name: talkvera-web
    labels:
      traefik.enable: "true"

      # root domain (menggunakan variabel dari .env)
      traefik.http.routers.talkvera-web.entrypoints: websecure
      traefik.http.routers.talkvera-web.rule: Host(`${ROOT_DOMAIN}`)
      traefik.http.routers.talkvera-web.service: talkvera
      traefik.http.routers.talkvera-web.tls.certresolver: mytlschallenge

      # www (dibuat secara dinamis dari variabel)
      traefik.http.routers.talkvera-www.entrypoints: websecure
      traefik.http.routers.talkvera-www.rule: Host(`www.${ROOT_DOMAIN}`)
      traefik.http.routers.talkvera-www.service: talkvera
      traefik.http.routers.talkvera-www.tls.certresolver: mytlschallenge

      traefik.http.services.talkvera.loadbalancer.server.port: "80"
    expose:
      - "80"
    restart: always
    networks:
      - default
networks:
  default:
    external: true
    name: root_default